nome=input("Digite um funcionário: ")
empresa=input("Digite um intituição: ")
qnt_funionarios=int(input("Digite a quantidade de funcionários:  "))
mediaMensalidade=float(input("Digite a média de mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("Possui: ", qnt_funionarios, "funcionários. ")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("=============Verifique os tipos de dados abaixo=============")
print("O tipo de dados da variavel [nome] é: ",type(nome))
print("O tipo de dados da variavel [empresa] é: ",type(empresa))
print("O tipo de dados da variavel [qnt_funcionarios] é: ",type(qnt_funionarios))
print("O tipo de dados da variavel [mediaMensalidade] é: ",type(mediaMensalidade))